'use client';
import React,{useEffect,useRef,useState} from 'react';
import {ApiClient} from '../lib/api-client';
type Crop={left:number;top:number;width:number;height:number};
const full:Crop={left:0,top:0,width:10000,height:10000};
export function ProfilePhoto({token,owner,initialAsset}:{token:string;owner:string;initialAsset?:string}){
 const [asset,setAsset]=useState(initialAsset),[selected,setSelected]=useState<{mimeType:string;dataBase64:string;image:HTMLImageElement}|null>(null),[crop,setCrop]=useState<Crop>(full),[status,setStatus]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[imageUrl,setImageUrl]=useState(''),[revision,setRevision]=useState(0);
 const current=useRef(owner),selection=useRef(0),canvas=useRef<HTMLCanvasElement>(null);current.current=owner;
 useEffect(()=>{setAsset(initialAsset);setSelected(null);setCrop(full);setStatus('');setError('');setBusy(false);selection.current++;},[owner,initialAsset]);
 useEffect(()=>{current.current=owner;return()=>{current.current='';selection.current++;};},[owner]);
 useEffect(()=>{
  let cancelled=false,timer:ReturnType<typeof setTimeout>|undefined,url='';setImageUrl('');
  if(!asset||!token)return;
  const mine=owner;
  async function check(){try{const result=await ApiClient.profilePhoto(`/media/${asset}/processing`,token);if(cancelled||current.current!==mine)return;setStatus(result.status);if(result.status==='READY'){const blob=await ApiClient.profileImage(asset!,token);if(cancelled||current.current!==mine)return;url=URL.createObjectURL(blob);setImageUrl(url);}else if(result.status==='PENDING'){timer=setTimeout(check,3000);}}catch{if(!cancelled)setError('फोटो लोड भएन। पुनः प्रयास गर्नुहोस्। / Photo unavailable; retry.');}}
  void check();return()=>{cancelled=true;if(timer)clearTimeout(timer);if(url)URL.revokeObjectURL(url);};
 },[asset,token,owner,revision]);
 useEffect(()=>{const context=canvas.current?.getContext('2d');if(!selected||!context||!canvas.current)return;const image=selected.image,w=Math.max(1,Math.floor(image.naturalWidth*crop.width/10000)),h=Math.max(1,Math.floor(image.naturalHeight*crop.height/10000)),scale=Math.min(256/w,256/h,1);canvas.current.width=Math.max(1,Math.round(w*scale));canvas.current.height=Math.max(1,Math.round(h*scale));context.drawImage(image,Math.floor(image.naturalWidth*crop.left/10000),Math.floor(image.naturalHeight*crop.top/10000),w,h,0,0,canvas.current.width,canvas.current.height);},[selected,crop]);
 async function choose(file?:File){const sequence=++selection.current,mine=owner;setError('');setSelected(null);if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('JPEG, PNG वा WebP, अधिकतम 10 MB / Choose JPEG, PNG or WebP up to 10 MB');return;}setBusy(true);try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const value=new Image();value.onload=()=>resolve(value);value.onerror=reject;value.src=data;});if(current.current!==mine||sequence!==selection.current)return;if(image.naturalWidth>8192||image.naturalHeight>8192||image.naturalWidth*image.naturalHeight>20000000)throw new Error('फोटो धेरै ठूलो छ / Image dimensions exceed the limit');setSelected({mimeType:file.type,dataBase64:data.split(',')[1],image});setCrop(full);}catch(e:any){if(current.current===mine&&sequence===selection.current)setError(e.message||'फोटो पढ्न सकिएन / Invalid image');}finally{if(current.current===mine&&sequence===selection.current)setBusy(false);}}
 async function upload(){if(!selected||busy)return;const mine=owner;setBusy(true);setError('');try{const result=await ApiClient.profilePhoto('/photo',token,'POST',{mimeType:selected.mimeType,dataBase64:selected.dataBase64,crop});if(current.current!==mine)return;setAsset(result.assetId);setSelected(null);setStatus('PENDING');}catch(e:any){if(current.current===mine)setError(e.message);}finally{if(current.current===mine)setBusy(false);}}
 async function remove(){const mine=owner;setBusy(true);try{const result=await ApiClient.profilePhoto('/photo',token,'DELETE');if(current.current!==mine)return;setAsset(undefined);setStatus(result.retainedForEvidence?'प्रमाणका लागि सुरक्षित राखिएको छ / Retained as evidence':'');}catch(e:any){if(current.current===mine)setError(e.message);}finally{if(current.current===mine)setBusy(false);}}
 async function retry(){if(!asset)return;try{await ApiClient.profilePhoto(`/media/${asset}/retry`,token,'POST');if(current.current===owner){setError('');setStatus('PENDING');setRevision(value=>value+1);}}catch(e:any){if(current.current===owner)setError(e.message);}}
 return <section className="bg-white border rounded-xl p-6 space-y-4" aria-label="प्रोफाइल फोटो / Profile photo">
  <h2 className="font-semibold">प्रोफाइल फोटो / Profile photo</h2>
  {imageUrl?<img src={imageUrl} alt="मेरो प्रोफाइल फोटो / My profile photo" className="w-24 h-24 object-cover rounded-full"/>:<div className="w-24 h-24 rounded-full bg-slate-100 flex items-center justify-center" aria-label="Photo placeholder">क</div>}
  <p className="text-sm" role="status">{status==='PENDING'?'फोटो तयार हुँदैछ / Processing photo':status==='FAILED'?'फोटो तयार भएन / Processing failed':status==='READY'?'फोटो तयार छ / Photo ready':status}</p>
  {error&&<p role="alert" className="text-red-700">{error}</p>}
  <label className="block">फोटो छान्नुहोस् / Choose photo<input aria-label="Choose profile photo" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>void choose(e.target.files?.[0])}/></label>
  {selected&&<div className="space-y-3"><canvas ref={canvas} aria-label="Photo crop preview" className="border"/><p className="text-sm">काट्ने क्षेत्र प्रतिशतमा छान्नुहोस् / Select crop area in percent</p><div className="flex flex-wrap gap-3">{(['left','top','width','height'] as const).map(field=><label key={field}>{({left:'बायाँ / Left',top:'माथि / Top',width:'चौडाइ / Width',height:'उचाइ / Height'})[field]}<input aria-label={`Crop ${field} percent`} type="number" step="1" min={field==='width'||field==='height'?1:0} max="100" value={crop[field]/100} disabled={busy} onChange={e=>{const value=Math.round(Number(e.target.value)*100);if(!Number.isFinite(value))return;setCrop(previous=>{const next={...previous,[field]:Math.max(field==='width'||field==='height'?100:0,Math.min(10000,value))};next.width=Math.min(next.width,10000-next.left);next.height=Math.min(next.height,10000-next.top);return next;});}} className="border rounded p-2 w-20 block"/></label>)}</div><button disabled={busy||crop.width<1||crop.height<1} onClick={()=>void upload()} className="border rounded p-2">काटेर सुरक्षित गर्नुहोस् / Save cropped photo</button><button disabled={busy} onClick={()=>{setSelected(null);selection.current++;}}>रद्द गर्नुहोस् / Cancel</button></div>}
  {(status==='FAILED'||status==='NOT_SCHEDULED'||error&&asset)&&<button onClick={()=>void retry()} disabled={busy}>पुनः प्रयास / Retry processing</button>}
  {asset&&<button onClick={()=>void remove()} disabled={busy} className="border rounded p-2">फोटो हटाउनुहोस् / Remove photo</button>}
 </section>;
}
