// ============================================================================
// Kashyap Adhikari Canonical 71 Nata/Saino Kinship Rules (Baseline v0.2 Draft)
// Source: Kashyap_Adhikari_Nata_Saino_Desk_Validated_Draft_v0.2.xlsx
// Status: Desk-Validated Draft | Open Gate HG-002: Pending Senior Cultural Sign-off
// ============================================================================

export interface CanonicalKinshipRule {
  ruleId: string;
  pathCode: string;
  relationshipName: string;
  nepaliTerm: string;
  romanization: string;
  englishLabel: string;
  reciprocalTerm: string;
  validationStatus: string;
  culturalReviewer: string;
  finalApprover: string;
}

export const CANONICAL_NATA_SAINO_RULES: CanonicalKinshipRule[] = [
  {
    "ruleId": "NS-001",
    "pathCode": "E",
    "relationshipName": "Self",
    "nepaliTerm": "आफू",
    "romanization": "aafu",
    "englishLabel": "Self",
    "reciprocalTerm": "N/A",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-002",
    "pathCode": "E-F",
    "relationshipName": "Father",
    "nepaliTerm": "बुबा",
    "romanization": "bubā",
    "englishLabel": "Father",
    "reciprocalTerm": "छोरा/छोरी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-003",
    "pathCode": "E-M",
    "relationshipName": "Mother",
    "nepaliTerm": "आमा",
    "romanization": "āmā",
    "englishLabel": "Mother",
    "reciprocalTerm": "छोरा/छोरी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-004",
    "pathCode": "E-B(o)",
    "relationshipName": "Older brother",
    "nepaliTerm": "दाजु",
    "romanization": "dāju",
    "englishLabel": "Older brother",
    "reciprocalTerm": "भाइ/बहिनी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-005",
    "pathCode": "E-B(y)",
    "relationshipName": "Younger brother",
    "nepaliTerm": "भाइ",
    "romanization": "bhāi",
    "englishLabel": "Younger brother",
    "reciprocalTerm": "दाजु/दिदी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-006",
    "pathCode": "E-Z(o)",
    "relationshipName": "Older sister",
    "nepaliTerm": "दिदी",
    "romanization": "didī",
    "englishLabel": "Older sister",
    "reciprocalTerm": "भाइ/बहिनी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-007",
    "pathCode": "E-Z(y)",
    "relationshipName": "Younger sister",
    "nepaliTerm": "बहिनी",
    "romanization": "bahinī",
    "englishLabel": "Younger sister",
    "reciprocalTerm": "दाजु/दिदी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-008",
    "pathCode": "E-H",
    "relationshipName": "Husband",
    "nepaliTerm": "श्रीमान्",
    "romanization": "shrīmān",
    "englishLabel": "Husband",
    "reciprocalTerm": "श्रीमती",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-009",
    "pathCode": "E-W",
    "relationshipName": "Wife",
    "nepaliTerm": "श्रीमती",
    "romanization": "shrīmatī",
    "englishLabel": "Wife",
    "reciprocalTerm": "श्रीमान्",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-010",
    "pathCode": "E-S",
    "relationshipName": "Son",
    "nepaliTerm": "छोरा",
    "romanization": "chorā",
    "englishLabel": "Son",
    "reciprocalTerm": "बुबा/आमा",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-011",
    "pathCode": "E-D",
    "relationshipName": "Daughter",
    "nepaliTerm": "छोरी",
    "romanization": "chorī",
    "englishLabel": "Daughter",
    "reciprocalTerm": "बुबा/आमा",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-012",
    "pathCode": "E-F-F",
    "relationshipName": "Father's father",
    "nepaliTerm": "हजुरबुबा",
    "romanization": "hajurbubā",
    "englishLabel": "Paternal grandfather",
    "reciprocalTerm": "नाति/नातिनी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-013",
    "pathCode": "E-F-M",
    "relationshipName": "Father's mother",
    "nepaliTerm": "हजुरआमा",
    "romanization": "hajurāmā",
    "englishLabel": "Paternal grandmother",
    "reciprocalTerm": "नाति/नातिनी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-014",
    "pathCode": "E-M-F",
    "relationshipName": "Mother's father",
    "nepaliTerm": "हजुरबुबा",
    "romanization": "hajurbubā",
    "englishLabel": "Maternal grandfather",
    "reciprocalTerm": "नाति/नातिनी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-015",
    "pathCode": "E-M-M",
    "relationshipName": "Mother's mother",
    "nepaliTerm": "हजुरआमा",
    "romanization": "hajurāmā",
    "englishLabel": "Maternal grandmother",
    "reciprocalTerm": "नाति/नातिनी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-016",
    "pathCode": "E-S-S / E-D-S",
    "relationshipName": "Child's son",
    "nepaliTerm": "नाति",
    "romanization": "nāti",
    "englishLabel": "Grandson",
    "reciprocalTerm": "हजुरबुबा/हजुरआमा",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-017",
    "pathCode": "E-S-D / E-D-D",
    "relationshipName": "Child's daughter",
    "nepaliTerm": "नातिनी",
    "romanization": "nātinī",
    "englishLabel": "Granddaughter",
    "reciprocalTerm": "हजुरबुबा/हजुरआमा",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-018",
    "pathCode": "E-*-*-S",
    "relationshipName": "Grandchild's son",
    "nepaliTerm": "पनाति",
    "romanization": "panāti",
    "englishLabel": "Great-grandson",
    "reciprocalTerm": "बराजु/बराज्यै",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-019",
    "pathCode": "E-*-*-D",
    "relationshipName": "Grandchild's daughter",
    "nepaliTerm": "पनातिनी",
    "romanization": "panātinī",
    "englishLabel": "Great-granddaughter",
    "reciprocalTerm": "बराजु/बराज्यै",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-020",
    "pathCode": "E-F-B(y)",
    "relationshipName": "Father's younger brother",
    "nepaliTerm": "काका",
    "romanization": "kākā",
    "englishLabel": "Paternal younger uncle",
    "reciprocalTerm": "भतिजा/भतिजी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-021",
    "pathCode": "E-F-B(y)-W",
    "relationshipName": "Father's younger brother's wife",
    "nepaliTerm": "काकी",
    "romanization": "kākī",
    "englishLabel": "Wife of paternal younger uncle",
    "reciprocalTerm": "भतिजा/भतिजी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-022",
    "pathCode": "E-F-B(o)",
    "relationshipName": "Father's older brother",
    "nepaliTerm": "ठूलोबुबा",
    "romanization": "ṭhūlobubā",
    "englishLabel": "Paternal elder uncle",
    "reciprocalTerm": "भतिजा/भतिजी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-023",
    "pathCode": "E-F-B(o)-W",
    "relationshipName": "Father's older brother's wife",
    "nepaliTerm": "ठूलीआमा",
    "romanization": "ṭhūlīāmā",
    "englishLabel": "Wife of paternal elder uncle",
    "reciprocalTerm": "भतिजा/भतिजी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-024",
    "pathCode": "E-F-Z",
    "relationshipName": "Father's sister",
    "nepaliTerm": "फुपू",
    "romanization": "phupū",
    "englishLabel": "Paternal aunt",
    "reciprocalTerm": "भतिजा/भतिजी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-025",
    "pathCode": "E-F-Z-H",
    "relationshipName": "Father's sister's husband",
    "nepaliTerm": "फुपाजु",
    "romanization": "phupāju",
    "englishLabel": "Husband of paternal aunt",
    "reciprocalTerm": "भतिजा/भतिजी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-026",
    "pathCode": "E-M-B",
    "relationshipName": "Mother's brother",
    "nepaliTerm": "मामा",
    "romanization": "māmā",
    "englishLabel": "Maternal uncle",
    "reciprocalTerm": "भाञ्जा/भाञ्जी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-027",
    "pathCode": "E-M-B-W",
    "relationshipName": "Mother's brother's wife",
    "nepaliTerm": "माइजू",
    "romanization": "māijū",
    "englishLabel": "Wife of maternal uncle",
    "reciprocalTerm": "भाञ्जा/भाञ्जी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-028",
    "pathCode": "E-M-Z(o)",
    "relationshipName": "Mother's older sister",
    "nepaliTerm": "आमाकी दिदी",
    "romanization": "āmākī didī",
    "englishLabel": "Maternal elder aunt",
    "reciprocalTerm": "भाञ्जा/भाञ्जी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-029",
    "pathCode": "E-M-Z(y)",
    "relationshipName": "Mother's younger sister",
    "nepaliTerm": "सानीआमा",
    "romanization": "sānīāmā",
    "englishLabel": "Maternal younger aunt",
    "reciprocalTerm": "भाञ्जा/भाञ्जी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-030",
    "pathCode": "E-M-Z(o)-H",
    "relationshipName": "Mother's older sister's husband",
    "nepaliTerm": "आमाकी दिदीका श्रीमान्",
    "romanization": "āmākī didīkā shrīmān",
    "englishLabel": "Husband of maternal elder aunt",
    "reciprocalTerm": "भाञ्जा/भाञ्जी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-031",
    "pathCode": "E-M-Z(y)-H",
    "relationshipName": "Mother's younger sister's husband",
    "nepaliTerm": "सानाबुबा",
    "romanization": "sānābubā",
    "englishLabel": "Husband of maternal younger aunt",
    "reciprocalTerm": "भाञ्जा/भाञ्जी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-032",
    "pathCode": "E-B-S",
    "relationshipName": "Brother's son",
    "nepaliTerm": "भतिजा",
    "romanization": "bhatijā",
    "englishLabel": "Nephew (brother's son)",
    "reciprocalTerm": "काका/फुपू",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-033",
    "pathCode": "E-B-D",
    "relationshipName": "Brother's daughter",
    "nepaliTerm": "भतिजी",
    "romanization": "bhatijī",
    "englishLabel": "Niece (brother's daughter)",
    "reciprocalTerm": "काका/फुपू",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-034",
    "pathCode": "E-Z-S",
    "relationshipName": "Sister's son",
    "nepaliTerm": "भाञ्जा",
    "romanization": "bhāñjā",
    "englishLabel": "Nephew (sister's son)",
    "reciprocalTerm": "मामा/माइजू",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-035",
    "pathCode": "E-Z-D",
    "relationshipName": "Sister's daughter",
    "nepaliTerm": "भाञ्जी",
    "romanization": "bhāñjī",
    "englishLabel": "Niece (sister's daughter)",
    "reciprocalTerm": "मामा/माइजू",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-036",
    "pathCode": "E-Z-H",
    "relationshipName": "Sister's husband",
    "nepaliTerm": "भिनाजु",
    "romanization": "bhināju",
    "englishLabel": "Brother-in-law (sister's husband)",
    "reciprocalTerm": "सालो/साली",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-037",
    "pathCode": "E-B(o)-W",
    "relationshipName": "Older brother's wife",
    "nepaliTerm": "भाउजू",
    "romanization": "bhāujū",
    "englishLabel": "Sister-in-law (older brother's wife)",
    "reciprocalTerm": "देवर/नन्द",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-038",
    "pathCode": "E-B(y)-W",
    "relationshipName": "Younger brother's wife",
    "nepaliTerm": "भाइबुहारी",
    "romanization": "bhāibuhārī",
    "englishLabel": "Younger brother's wife",
    "reciprocalTerm": "जेठाजु/नन्द",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-039",
    "pathCode": "E-S-W",
    "relationshipName": "Son's wife",
    "nepaliTerm": "बुहारी",
    "romanization": "buhārī",
    "englishLabel": "Daughter-in-law",
    "reciprocalTerm": "ससुरा/सासू",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-040",
    "pathCode": "E-D-H",
    "relationshipName": "Daughter's husband",
    "nepaliTerm": "ज्वाइँ",
    "romanization": "jvāĩ",
    "englishLabel": "Son-in-law",
    "reciprocalTerm": "ससुरा/सासू",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-041",
    "pathCode": "E-SP-F",
    "relationshipName": "Spouse's father",
    "nepaliTerm": "ससुरा",
    "romanization": "sasurā",
    "englishLabel": "Father-in-law",
    "reciprocalTerm": "ज्वाइँ/बुहारी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-042",
    "pathCode": "E-SP-M",
    "relationshipName": "Spouse's mother",
    "nepaliTerm": "सासू",
    "romanization": "sāsū",
    "englishLabel": "Mother-in-law",
    "reciprocalTerm": "ज्वाइँ/बुहारी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-043",
    "pathCode": "E-H-B(o)",
    "relationshipName": "Husband's older brother",
    "nepaliTerm": "जेठाजु",
    "romanization": "jeṭhāju",
    "englishLabel": "Husband's older brother",
    "reciprocalTerm": "बुहारी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-044",
    "pathCode": "E-H-B(y)",
    "relationshipName": "Husband's younger brother",
    "nepaliTerm": "देवर",
    "romanization": "devar",
    "englishLabel": "Husband's younger brother",
    "reciprocalTerm": "भाउजू",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-045",
    "pathCode": "E-H-Z",
    "relationshipName": "Husband's sister",
    "nepaliTerm": "नन्द",
    "romanization": "nanda",
    "englishLabel": "Husband's sister",
    "reciprocalTerm": "भाउजू",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-046",
    "pathCode": "E-H-B(o)-W",
    "relationshipName": "Husband's older brother's wife",
    "nepaliTerm": "जेठानी",
    "romanization": "jeṭhānī",
    "englishLabel": "Co-sister (elder brother's wife)",
    "reciprocalTerm": "देवरानी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-047",
    "pathCode": "E-H-B(y)-W",
    "relationshipName": "Husband's younger brother's wife",
    "nepaliTerm": "देवरानी",
    "romanization": "devarānī",
    "englishLabel": "Co-sister (younger brother's wife)",
    "reciprocalTerm": "जेठानी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-048",
    "pathCode": "E-W-B(o)",
    "relationshipName": "Wife's older brother",
    "nepaliTerm": "जेठान",
    "romanization": "jeṭhān",
    "englishLabel": "Wife's older brother",
    "reciprocalTerm": "भिनाजु",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-049",
    "pathCode": "E-W-B(y)",
    "relationshipName": "Wife's younger brother",
    "nepaliTerm": "सालो",
    "romanization": "sālo",
    "englishLabel": "Wife's younger brother",
    "reciprocalTerm": "भिनाजु",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-050",
    "pathCode": "E-W-Z(o)",
    "relationshipName": "Wife's older sister",
    "nepaliTerm": "जेठी साली",
    "romanization": "jeṭhī sālī",
    "englishLabel": "Wife's older sister",
    "reciprocalTerm": "भिनाजु",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-051",
    "pathCode": "E-W-Z(y)",
    "relationshipName": "Wife's younger sister",
    "nepaliTerm": "साली",
    "romanization": "sālī",
    "englishLabel": "Wife's younger sister",
    "reciprocalTerm": "भिनाजु",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-052",
    "pathCode": "E-CHILD-SP-PARENT",
    "relationshipName": "Child's spouse's father",
    "nepaliTerm": "सम्धी",
    "romanization": "samdhī",
    "englishLabel": "Co-father-in-law",
    "reciprocalTerm": "सम्धी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-053",
    "pathCode": "E-CHILD-SP-PARENT",
    "relationshipName": "Child's spouse's mother",
    "nepaliTerm": "सम्धिनी",
    "romanization": "samdhinī",
    "englishLabel": "Co-mother-in-law",
    "reciprocalTerm": "सम्धिनी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-054",
    "pathCode": "E-F-B-CHILD",
    "relationshipName": "Paternal uncle's child",
    "nepaliTerm": "काकाको/ठूलोबुबाको छोरा वा छोरी",
    "romanization": "—",
    "englishLabel": "Paternal parallel cousin",
    "reciprocalTerm": "Path-dependent",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-055",
    "pathCode": "E-F-Z-CHILD",
    "relationshipName": "Paternal aunt's child",
    "nepaliTerm": "फुपूको छोरा वा छोरी",
    "romanization": "—",
    "englishLabel": "Paternal cross-cousin",
    "reciprocalTerm": "Path-dependent",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-056",
    "pathCode": "E-M-B-CHILD",
    "relationshipName": "Maternal uncle's child",
    "nepaliTerm": "मामाको छोरा वा छोरी",
    "romanization": "—",
    "englishLabel": "Maternal cross-cousin",
    "reciprocalTerm": "Path-dependent",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-057",
    "pathCode": "E-M-Z-CHILD",
    "relationshipName": "Maternal aunt's child",
    "nepaliTerm": "आमाकी दिदी/बहिनीको छोरा वा छोरी",
    "romanization": "—",
    "englishLabel": "Maternal parallel cousin",
    "reciprocalTerm": "Path-dependent",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-058",
    "pathCode": "E-AP(F)",
    "relationshipName": "Adoptive father",
    "nepaliTerm": "दत्तक पिता",
    "romanization": "dattak pitā",
    "englishLabel": "Adoptive father",
    "reciprocalTerm": "दत्तक छोरा/छोरी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-059",
    "pathCode": "E-AP(M)",
    "relationshipName": "Adoptive mother",
    "nepaliTerm": "दत्तक माता",
    "romanization": "dattak mātā",
    "englishLabel": "Adoptive mother",
    "reciprocalTerm": "दत्तक छोरा/छोरी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-060",
    "pathCode": "E-AC(S)",
    "relationshipName": "Adopted son",
    "nepaliTerm": "दत्तक छोरा",
    "romanization": "dattak chorā",
    "englishLabel": "Adopted son",
    "reciprocalTerm": "दत्तक पिता/माता",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-061",
    "pathCode": "E-AC(D)",
    "relationshipName": "Adopted daughter",
    "nepaliTerm": "दत्तक छोरी",
    "romanization": "dattak chorī",
    "englishLabel": "Adopted daughter",
    "reciprocalTerm": "दत्तक पिता/माता",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-062",
    "pathCode": "E-STP(F)",
    "relationshipName": "Stepfather",
    "nepaliTerm": "सौतेलो बुबा",
    "romanization": "sautelo bubā",
    "englishLabel": "Stepfather",
    "reciprocalTerm": "सौतेलो छोरा/सौतेली छोरी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-063",
    "pathCode": "E-STP(M)",
    "relationshipName": "Stepmother",
    "nepaliTerm": "सौतेली आमा",
    "romanization": "sautelī āmā",
    "englishLabel": "Stepmother",
    "reciprocalTerm": "सौतेलो छोरा/सौतेली छोरी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-064",
    "pathCode": "E-STB",
    "relationshipName": "Stepbrother",
    "nepaliTerm": "सौतेनी दाजु/भाइ",
    "romanization": "sautenī dāju/bhāi",
    "englishLabel": "Stepbrother",
    "reciprocalTerm": "Path-dependent",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-065",
    "pathCode": "E-STZ",
    "relationshipName": "Stepsister",
    "nepaliTerm": "सौतेनी दिदी/बहिनी",
    "romanization": "sautenī didī/bahinī",
    "englishLabel": "Stepsister",
    "reciprocalTerm": "Path-dependent",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-066",
    "pathCode": "E-HB",
    "relationshipName": "Half-brother",
    "nepaliTerm": "एकै बुबा वा आमातर्फका दाजु/भाइ",
    "romanization": "ekai bubā vā āmātarphakā dāju/bhāi",
    "englishLabel": "Half-brother",
    "reciprocalTerm": "Path-dependent",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-067",
    "pathCode": "E-HZ",
    "relationshipName": "Half-sister",
    "nepaliTerm": "एकै बुबा वा आमातर्फकी दिदी/बहिनी",
    "romanization": "ekai bubā vā āmātarphakī didī/bahinī",
    "englishLabel": "Half-sister",
    "reciprocalTerm": "Path-dependent",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-068",
    "pathCode": "E-GUARD",
    "relationshipName": "Legal/customary guardian",
    "nepaliTerm": "अभिभावक",
    "romanization": "abhibhāvak",
    "englishLabel": "Guardian",
    "reciprocalTerm": "आश्रित/संरक्षित व्यक्ति",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-069",
    "pathCode": "E-XSP",
    "relationshipName": "Divorced/separated spouse",
    "nepaliTerm": "पूर्व पति/पत्नी",
    "romanization": "pūrva pati/patnī",
    "englishLabel": "Former spouse",
    "reciprocalTerm": "पूर्व पति/पत्नी",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-070",
    "pathCode": "E-?",
    "relationshipName": "Unknown parentage/path",
    "nepaliTerm": "सम्बन्ध पुष्टि हुन बाँकी",
    "romanization": "—",
    "englishLabel": "Relationship awaiting confirmation",
    "reciprocalTerm": "N/A",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  },
  {
    "ruleId": "NS-071",
    "pathCode": "E-!",
    "relationshipName": "Disputed relationship",
    "nepaliTerm": "विवादित सम्बन्ध",
    "romanization": "—",
    "englishLabel": "Disputed relationship",
    "reciprocalTerm": "N/A",
    "validationStatus": "Expert validation required",
    "culturalReviewer": "",
    "finalApprover": ""
  }
];
