// ============================================================================
// Kashyap Adhikari Family Tree — Core Domain Enums
// ============================================================================

export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CENTRAL_ADMIN = 'CENTRAL_ADMIN',
  BRANCH_ADMIN = 'BRANCH_ADMIN',
  BRANCH_VERIFIER = 'BRANCH_VERIFIER',
  CULTURAL_HISTORIAN = 'CULTURAL_HISTORIAN',
  COMMUNITY_MODERATOR = 'COMMUNITY_MODERATOR',
  VERIFIED_MEMBER = 'VERIFIED_MEMBER',
  REGISTERED_USER = 'REGISTERED_USER',
  GUEST = 'GUEST'
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  UNKNOWN = 'UNKNOWN'
}

export enum LivingStatus {
  LIVING = 'LIVING',
  DECEASED = 'DECEASED',
  UNKNOWN = 'UNKNOWN'
}

export enum ParentType {
  BIOLOGICAL = 'BIOLOGICAL',
  ADOPTIVE = 'ADOPTIVE'
}

export enum SpouseStatus {
  CURRENT = 'CURRENT',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
  SEPARATED = 'SEPARATED'
}

export enum ClaimStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  IN_REVIEW = 'IN_REVIEW',
  ADDITIONAL_INFO_REQUESTED = 'ADDITIONAL_INFO_REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED'
}

export enum ChangeRequestType {
  NEW_PERSON = 'NEW_PERSON',
  EDIT_PERSON = 'EDIT_PERSON',
  RECORD_DEATH = 'RECORD_DEATH',
  ADD_PARENT_LINK = 'ADD_PARENT_LINK',
  REMOVE_PARENT_LINK = 'REMOVE_PARENT_LINK',
  ADD_SPOUSE_LINK = 'ADD_SPOUSE_LINK',
  REMOVE_SPOUSE_LINK = 'REMOVE_SPOUSE_LINK',
  MERGE_PERSON = 'MERGE_PERSON'
}

export enum ChangeRequestStatus {
  PENDING = 'PENDING',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED'
}

export enum DuplicateCandidateStatus {
  DETECTED = 'DETECTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  CONFIRMED_DUPLICATE = 'CONFIRMED_DUPLICATE',
  NOT_A_DUPLICATE = 'NOT_A_DUPLICATE',
  MERGED = 'MERGED'
}

export enum RuleSetStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED'
}

export enum RuleType {
  NATA_SAINO = 'NATA_SAINO',
  JUTHO_SUTOK = 'JUTHO_SUTOK',
  TITHI_SHRADDHA = 'TITHI_SHRADDHA',
  MARRIAGE_ELIGIBILITY = 'MARRIAGE_ELIGIBILITY'
}

export enum EventType {
  BRATABANDHA = 'BRATABANDHA',
  BIWAHA = 'BIWAHA',
  PASNI = 'PASNI',
  CHHWARI = 'CHHWARI',
  GUNYO_CHOLI = 'GUNYO_CHOLI',
  CHAURASI_PUJA = 'CHAURASI_PUJA',
  SHRADDHA = 'SHRADDHA',
  KUL_PUJA = 'KUL_PUJA',
  COMMUNITY_MEETING = 'COMMUNITY_MEETING',
  GENERAL_EVENT = 'GENERAL_EVENT'
}

export enum RsvpStatus {
  INVITED = 'INVITED',
  ATTENDING = 'ATTENDING',
  NOT_ATTENDING = 'NOT_ATTENDING',
  MAYBE = 'MAYBE'
}

export enum PostStatus {
  PENDING_MODERATION = 'PENDING_MODERATION',
  PUBLISHED = 'PUBLISHED',
  FLAGGED = 'FLAGGED',
  REMOVED = 'REMOVED'
}

export enum PrivacyVisibility {
  PUBLIC = 'PUBLIC',
  VERIFIED_COMMUNITY = 'VERIFIED_COMMUNITY',
  IMMEDIATE_FAMILY = 'IMMEDIATE_FAMILY',
  PRIVATE = 'PRIVATE'
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  CLAIM_SUBMIT = 'CLAIM_SUBMIT',
  CLAIM_APPROVE = 'CLAIM_APPROVE',
  CLAIM_REJECT = 'CLAIM_REJECT',
  CHANGE_REQUEST_APPROVE = 'CHANGE_REQUEST_APPROVE',
  CHANGE_REQUEST_REJECT = 'CHANGE_REQUEST_REJECT',
  MERGE_EXECUTE = 'MERGE_EXECUTE',
  ROLE_ASSIGN = 'ROLE_ASSIGN',
  ROLE_REVOKE = 'ROLE_REVOKE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  RULE_ACTIVATE = 'RULE_ACTIVATE'
}

export enum LanguageCode {
  NEPALI = 'ne',
  ENGLISH = 'en'
}
