'use client';
import {useEffect,useRef,useState} from 'react';
import {useAuth} from '../../context/auth-context';
const API=process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:3000';
export default function MediaOperations(){
 const {user,accessToken,isLoading}=useAuth();const [runs,setRuns]=useState<any[]>([]),[report,setReport]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string[]>([]),[notice,setNotice]=useState(''),[after,setAfter]=useState('0'),[reason,setReason]=useState('');
 const generation=useRef(0),current=useRef(user?.id);current.current=user?.id;
 async function request(path='',method='GET',data?:any){const response=await fetch(`${API}/media-operations/inventories${path}`,{method,headers:{Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json'},cache:'no-store',...(data?{body:JSON.stringify(data)}:{})});const result=await response.json();if(!response.ok)throw new Error(result.message||'Operation unavailable');return result;}
 useEffect(()=>{const mine=++generation.current;setReport(null);setSelected([]);setReason('');setNotice('');setError('');setBusy(false);if(!accessToken){setRuns([]);return;}void request().then(value=>{if(mine===generation.current)setRuns(value);}).catch(e=>{if(mine===generation.current)setError(e.message);});return()=>{generation.current++;};},[accessToken,user?.id]);
 async function operate(work:()=>Promise<any>,runId?:string,cursor='0'){
  if(busy)return;const mine=generation.current,owner=user?.id;setBusy(true);setError('');setNotice('');
  try{const result=await work();if(mine!==generation.current||current.current!==owner)return;const id=runId||result?.id;if(id){const value=await request(`/${id}?after=${cursor}`);if(mine!==generation.current)return;setReport(value);setAfter(cursor);setSelected([]);setReason('');}const list=await request();if(mine!==generation.current)return;setRuns(list);if(result?.scheduled!==undefined)setNotice(`Scheduled: ${result.scheduled}${result.skipped!==undefined?`; skipped: ${result.skipped}`:''}`);}catch(e:any){if(mine===generation.current)setError(e.message);}finally{if(mine===generation.current)setBusy(false);}
 }
 const recoveryIds=report?.items.filter((item:any)=>selected.includes(String(item.id))&&['IMAGE_JOB_MISSING','DELETION_QUEUE_MISSING'].includes(item.finding)).map((item:any)=>String(item.id))||[];
 const migrationIds=report?.items.filter((item:any)=>selected.includes(String(item.id))&&item.finding==='LEGACY_MIGRATION_REVIEW').map((item:any)=>String(item.id))||[];
 const orphanIds=report?.items.filter((item:any)=>selected.includes(String(item.id))&&['ABANDONED_UPLOAD_REVIEW','CLEANUP_FENCED'].includes(item.finding)).map((item:any)=>String(item.id))||[];
 if(isLoading)return <p>लोड हुँदैछ / Loading</p>;
 if(!user||!accessToken)return <p>साइन इन गर्नुहोस् / Sign in to continue</p>;
 return <section className="space-y-5"><h1 className="text-2xl font-bold">मिडिया सञ्चालन / Media operations</h1><p>Check private storage and resume interrupted inventories. Findings describe observations at scan time. Recovery schedules eligible existing assets after checking their current state.</p><p>Only expired journaled uploads can be approved for cleanup after review. Untracked objects remain for reconciliation; legal holds cannot be released here. Reviewed legacy migration copies verified bytes to private storage and retains local source files.</p>
 {error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <button className="border rounded p-2" disabled={busy||runs.some(r=>r.status==='RUNNING')} onClick={()=>void operate(()=>request('','POST',{}))}>नयाँ जाँच / Start inventory</button>
 <ul>{runs.map(run=><li key={run.id}><button disabled={busy} className="underline py-2" onClick={()=>void operate(()=>request(`/${run.id}`),run.id)}>{run.status} · {run.phase} · {new Date(run.created_at).toLocaleString()}</button></li>)}</ul>
 {report&&<div className="space-y-4"><h2 className="text-lg font-semibold">{report.run.status} · {report.run.phase}</h2>
 {report.run.status==='RUNNING'&&<div className="flex gap-3"><button disabled={busy} className="border rounded p-2" onClick={()=>void operate(()=>request(`/${report.run.id}/advance`,'POST',{}),report.run.id)}>अर्को चरण जाँच / Scan next batch</button><button disabled={busy} className="border rounded p-2" onClick={()=>void operate(()=>request(`/${report.run.id}/cancel`,'POST',{}),report.run.id)}>जाँच रोक्नुहोस् / Cancel inventory</button></div>}
 <ul>{report.summary.map((entry:any)=><li key={entry.finding}>{entry.finding}: {entry.count}</li>)}</ul>
 <table className="w-full text-left text-sm"><caption className="text-left">जाँच विवरण / Inventory findings</caption><thead><tr><th>Select</th><th>Finding</th><th>Asset</th><th>Area</th><th>Upload / cleanup</th></tr></thead><tbody>{report.items.map((item:any)=><tr key={item.id} className="border-b"><td>{report.run.status==='COMPLETE'&&['IMAGE_JOB_MISSING','DELETION_QUEUE_MISSING','ABANDONED_UPLOAD_REVIEW','CLEANUP_FENCED','LEGACY_MIGRATION_REVIEW'].includes(item.finding)&&!['PENDING','PROCESSED'].includes(item.cleanup_status)&&!['PENDING','PROCESSED'].includes(item.migration_status)&&<input type="checkbox" aria-label={`Select finding ${item.id}`} checked={selected.includes(String(item.id))} disabled={busy||!selected.includes(String(item.id))&&selected.length>=20} onChange={e=>setSelected(previous=>e.target.checked?[...previous,String(item.id)]:previous.filter(id=>id!==String(item.id)))}/>}</td><td>{item.finding}</td><td>{item.asset_id||item.item_key.slice(0,12)}</td><td>{item.bucket}</td><td>{item.migration_status||item.cleanup_status||item.upload_state}{item.expected_type&&<p>{item.expected_type} · {item.expected_bytes} bytes</p>}{item.expected_checksum&&<p className="font-mono break-all">SHA256 {item.expected_checksum}</p>}{item.cleanup_error&&<p>{item.cleanup_error}</p>}{item.migration_error&&<p>{item.migration_error}</p>}</td></tr>)}</tbody></table>
 {after!=='0'&&<button disabled={busy} onClick={()=>void operate(()=>request(`/${report.run.id}`),report.run.id)}>First page</button>}{report.next&&<button disabled={busy} onClick={()=>void operate(()=>request(`/${report.run.id}?after=${report.next}`),report.run.id,report.next)}>Next findings</button>}
 {recoveryIds.length>0&&<button disabled={busy} className="border rounded p-2" onClick={()=>{if(window.confirm('Schedule selected image/deletion jobs? Current permissions and legal holds will be checked.'))void operate(()=>request(`/${report.run.id}/recover`,'POST',{itemIds:recoveryIds}),report.run.id,after);}}>चयन गरिएको पुनःस्थापना / Schedule selected recovery</button>}
 {(orphanIds.length>0||migrationIds.length>0)&&<div className="space-y-2"><label className="block">समीक्षाको कारण / Review reason<textarea aria-label="Review reason" className="border rounded p-2 block w-full" maxLength={1000} disabled={busy} value={reason} onChange={e=>setReason(e.target.value)}/></label>{migrationIds.length>0&&<button disabled={busy||reason.trim().length<5} className="border rounded p-2" onClick={()=>{if(window.confirm(`Copy ${migrationIds.length} verified legacy assets to private storage? Original local files will be retained.`))void operate(()=>request(`/${report.run.id}/legacy-migration`,'POST',{itemIds:migrationIds,reason}),report.run.id,after);}}>स्थानान्तरण स्वीकृत गर्नुहोस् / Approve legacy migration</button>}{orphanIds.length>0&&<button disabled={busy||reason.trim().length<5} className="border border-red-700 text-red-800 rounded p-2" onClick={()=>{if(window.confirm(`Approve permanent deletion of ${orphanIds.length} selected expired uploads? References, checksums and legal holds will be rechecked.`))void operate(()=>request(`/${report.run.id}/orphan-cleanup`,'POST',{itemIds:orphanIds,reason}),report.run.id,after);}}>सफाइ स्वीकृत गर्नुहोस् / Approve orphan cleanup</button>}</div>}
 </div>}
 </section>;
}
