import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { API, login, headers } from './helpers/auth';

test('Community publication, likes, comments and reports persist through authenticated browser workflows',async({page,browser})=>{
 test.setTimeout(120000);
 const reviewerContext=await browser.newContext();
 try {
  await login(page,'9800000002');await page.goto('/community');
  const title=`Fictional community ${randomUUID()}`;
  await page.getByLabel('शीर्षक (Title)',{exact:true}).fill(title);
  await page.getByLabel('सन्देश (Message)',{exact:true}).fill('Fictional family gathering discussion for browser acceptance.');
  const branchResponse=await page.request.get(`${API}/genealogy/branches`);expect(branchResponse.ok()).toBeTruthy();
  const branch=(await branchResponse.json()).find((b:any)=>b.code==='KASKI');
  await page.getByLabel('दायरा (Audience)').selectOption(branch.id);
  await page.getByLabel('प्रकार (Category)').selectOption('ASSISTANCE');
  await page.getByRole('button',{name:/Submit for review/}).click();
  await expect(page.getByRole('status')).toContainText('Submitted for independent moderation');
  const authorCard=page.getByRole('article',{name:title});await expect(authorCard).toContainText('PENDING');
  await expect(authorCard.getByRole('button',{name:/Review/})).toHaveCount(0);
  const reviewer=await reviewerContext.newPage();await login(reviewer);await reviewer.goto('/community');
  await reviewer.getByRole('button',{name:/Moderation queue/}).click();
  const reviewCard=reviewer.getByRole('article',{name:title});await reviewCard.getByRole('button',{name:/Review/}).click();
  await reviewer.getByRole('dialog').getByLabel(/Reason \/ notes/).fill('Independent fictional content review approved.');
  await reviewer.getByRole('dialog').getByRole('button',{name:/Publish/}).click();
  await expect(reviewer.getByRole('dialog')).toHaveCount(0);
  await page.reload();await expect(authorCard).toContainText('PUBLISHED');
  await authorCard.getByRole('button',{name:/Edit/}).click();
  const edit=page.getByRole('dialog',{name:'Edit community post'});
  await edit.getByRole('textbox',{name:'Edit message',exact:true}).fill('Revised fictional gathering details.');
  await edit.getByLabel('Edit reason').fill('Correct the gathering details.');
  await edit.getByRole('button',{name:'Save for review'}).click();
  await expect(edit).toHaveCount(0);await expect(authorCard).toContainText('PENDING');
  await authorCard.getByRole('button',{name:/Revision history/}).click();
  const history=page.getByRole('dialog',{name:'Community revision history'});
  await expect(history).toContainText('Revised fictional gathering details.');
  await expect(history).toContainText('Fictional family gathering discussion for browser acceptance.');
  await history.getByRole('button',{name:'Close history'}).click();
  await reviewer.getByRole('button',{name:/Refresh/}).click();
  await reviewCard.getByRole('button',{name:/Review/}).click();
  await reviewer.getByRole('dialog').getByLabel(/Reason \/ notes/).fill('Independently reviewed revised gathering details.');
  await reviewer.getByRole('dialog').getByRole('button',{name:/Publish/}).click();
  await expect(reviewer.getByRole('dialog')).toHaveCount(0);
  await page.reload();await expect(authorCard).toContainText('PUBLISHED');
  await authorCard.getByRole('button',{name:/Moderation history/}).click();
  const decisions=page.getByRole('dialog',{name:'Community moderation history'});
  await expect(decisions).toContainText('Independent fictional content review approved.');
  await expect(decisions).toContainText('Independently reviewed revised gathering details.');
  await decisions.getByRole('button',{name:'Close moderation history'}).click();
  await authorCard.getByRole('button',{name:/Add image/}).click();
  const imageDialog=page.getByRole('dialog',{name:'Add community image'});
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAEUlEQVQImWMQCdYVCdZlgFAAD9oCUV/9UZEAAAAASUVORK5CYII=','base64');
  await imageDialog.getByLabel('Community image file',{exact:true}).setInputFiles({name:'fictional.png',mimeType:'image/png',buffer:png});
  await imageDialog.getByLabel('Image change reason',{exact:true}).fill('Add a fictional gathering image.');
  await imageDialog.getByRole('button',{name:'Submit image for review'}).click();
  await expect(imageDialog).toHaveCount(0);await expect(authorCard).toContainText('PENDING');
  await reviewer.getByRole('button',{name:/Refresh/}).click();await reviewCard.getByRole('button',{name:/Review/}).click();
  await reviewer.getByRole('dialog').getByLabel(/Reason \/ notes/).fill('Independent fictional image approval.');
  await reviewer.getByRole('dialog').getByRole('button',{name:/Publish/}).click();await expect(reviewer.getByRole('dialog')).toHaveCount(0);
  await page.reload();await expect(authorCard).toContainText('PUBLISHED');
  const downloading=page.waitForEvent('download');await authorCard.getByRole('button',{name:'Original image',exact:true}).click();
  const downloaded=await downloading;expect(downloaded.suggestedFilename()).toMatch(/^community_.*\.png$/);
  await authorCard.getByRole('button',{name:/Location\/contact sharing/}).click();
  const sharing=page.getByRole('dialog',{name:'Community location and contact sharing'});
  await expect(sharing.getByRole('checkbox',{name:/I consent to share/})).not.toBeChecked();
  await sharing.getByLabel('Community district',{exact:true}).fill('Kaski');await sharing.getByLabel('Community municipality',{exact:true}).fill('Pokhara');
  await sharing.getByLabel('Sharing change reason',{exact:true}).fill('Retain approximate private locality for review.');
  await sharing.getByRole('button',{name:'Save sharing for review'}).click();await expect(sharing).toHaveCount(0);await expect(authorCard).toContainText('PENDING');
  await expect(authorCard).toContainText('Kaski · Pokhara');
  await reviewer.getByRole('button',{name:/Refresh/}).click();await reviewCard.getByRole('button',{name:/Review/}).click();
  await reviewer.getByRole('dialog').getByLabel(/Reason \/ notes/).fill('Review private approximate locality.');await reviewer.getByRole('dialog').getByRole('button',{name:/Publish/}).click();await expect(reviewer.getByRole('dialog')).toHaveCount(0);
  await page.reload();await expect(authorCard).toContainText('PUBLISHED');
  await authorCard.getByRole('button',{name:/Like/}).click();
  await expect(authorCard.getByRole('button',{name:/Like/})).toHaveAttribute('aria-pressed','true');
  await authorCard.getByRole('button',{name:/Comments/}).click();
  await authorCard.getByLabel(/Your comment/).fill('Persist this fictional reply.');
  await authorCard.getByRole('button',{name:/Send comment/}).click();
  await expect(authorCard.getByText('Persist this fictional reply.',{exact:true})).toBeVisible();
  await authorCard.getByRole('button',{name:'Reply to comment: Persist this fictional reply.',exact:true}).click();
  await expect(authorCard.getByText('Replying to: Persist this fictional reply.',{exact:true})).toBeVisible();
  await authorCard.getByLabel(/Your comment/).fill('A fictional nested reply.');
  await authorCard.getByRole('button',{name:/Send comment/}).click();
  await expect(authorCard.getByText('A fictional nested reply.',{exact:true})).toBeVisible();
  await expect(authorCard.getByText('Reply to: Persist this fictional reply.',{exact:true})).toBeVisible();

  await page.reload();await expect(authorCard.getByRole('button',{name:/Like/})).toHaveAttribute('aria-pressed','true');
  const posts=await page.request.get(`${API}/community/posts`,{headers:await headers(page)});expect(posts.ok()).toBeTruthy();
  const post=(await posts.json()).find((p:any)=>p.title===title);expect(post.category).toBe('ASSISTANCE');expect(post.likesCount).toBe(1);expect(post.commentsCount).toBe(2);
  for(let n=0;n<51;n++)expect((await page.request.post(`${API}/community/posts/${post.id}/comments`,{headers:await headers(page),data:{content:`Fictional pagination comment ${n}`}})).ok()).toBeTruthy();
  await authorCard.getByRole('button',{name:/Comments/}).click();
  await expect(authorCard).toContainText('50 loaded');
  await authorCard.getByRole('button',{name:'Older comments',exact:true}).click();
  await expect(authorCard).toContainText('53 loaded');
  await expect(authorCard.getByText('A fictional nested reply.',{exact:true})).toBeVisible();
  await expect(authorCard.getByRole('button',{name:'Older comments',exact:true})).toBeDisabled();
  await authorCard.getByRole('button',{name:'Latest comments',exact:true}).click();
  await expect(authorCard).toContainText('50 loaded');

  await reviewer.getByRole('button',{name:/Feed/}).click();
  await reviewCard.getByRole('button',{name:'रिपोर्ट (Report)',exact:true}).click();
  await reviewer.getByRole('dialog').getByLabel(/Reason \/ notes/).fill('Fictional report for a second moderation review.');
  await reviewer.getByRole('dialog').getByRole('button',{name:/Submit report/}).click();
  await expect(reviewer.getByRole('dialog')).toHaveCount(0);
  await page.reload();await expect(authorCard).toContainText('PENDING');
  await expect(authorCard.getByRole('button',{name:/Like/})).toHaveCount(0);
  await expect(authorCard.getByRole('button',{name:/Report evidence/})).toHaveCount(0);
  await reviewer.getByRole('button',{name:/Moderation queue/}).click();
  await reviewCard.getByRole('button',{name:/Report evidence/}).click();
  const evidence=reviewer.getByRole('dialog',{name:'Community report evidence'});
  await expect(evidence).toContainText('Fictional report for a second moderation review.');
  await expect(evidence.getByRole('button',{name:'Older reports'})).toBeDisabled();
  await evidence.getByRole('button',{name:'Close report evidence'}).click();
  reviewer.once('dialog',dialog=>dialog.accept('Escalate fictional case for central review.'));
  await reviewCard.getByRole('button',{name:/Escalate to central/}).click();
  await expect(reviewCard).toContainText('Escalated: awaiting independent central review.');
  await reviewCard.getByRole('button',{name:/Report evidence/}).click();
  await expect(evidence).toContainText('Escalate fictional case for central review.');
  await expect(evidence).toContainText('OPEN');
  await evidence.getByRole('button',{name:'Close report evidence'}).click();

 } finally {await reviewerContext.close();}
});
