import { test, expect } from '@playwright/test';
import { login, API } from './helpers/auth';
test('Super Admin stages source data, revalidates after reload and erases payload with retained reports',async({page})=>{
 await login(page);const response=await page.request.get(`${API}/genealogy/branches`);expect(response.ok()).toBeTruthy();const branches=await response.json();const branchId=(Array.isArray(branches)?branches:branches.items)[0].id;
 const datasetKey=`FICTIONAL_BROWSER_${Date.now()}`,name='काल्पनिक आयात परीक्षण';
 const source={schemaVersion:1,datasetKey,branchId,sourceDescription:'Fictional browser-only source fixture',persons:[{sourceId:'PER-BROWSER-1',nameNepali:name,gender:'UNKNOWN',livingStatus:'LIVING',generation:1,sourceRef:'SRC-BROWSER-1',consent:'PENDING',verification:'VERIFIED',visibility:'PRIVATE'}],parentLinks:[]};
 await page.goto('/imports');await page.getByLabel('स्रोत JSON (Source JSON)').fill(JSON.stringify(source));await page.getByRole('button',{name:/Stage source/}).click();const staged=page.getByRole('region',{name:'Staged source'});await expect(staged).toContainText(datasetKey);
 await page.getByLabel('समीक्षाको कारण (Review reason)').fill('Fictional browser first validation');await page.getByRole('button',{name:/Run validation and reconciliation/}).click();const reports=page.getByRole('region',{name:'Import reports'});await expect(reports).toContainText('Consent review required');await expect(reports).toContainText('Production promotion blocked');
 await page.reload();await page.getByRole('button',{name:new RegExp(datasetKey)}).click();await expect(reports).toContainText('Fictional browser first validation');await page.getByLabel('समीक्षाको कारण (Review reason)').fill('Fictional browser second validation');await page.getByRole('button',{name:/Run validation and reconciliation/}).click();await expect(reports).toContainText('Fictional browser second validation');await expect(reports).toContainText('Fictional browser first validation');
 await page.getByLabel('समीक्षाको कारण (Review reason)').fill('Fictional browser payload erasure');await page.getByLabel(/Confirm permanent erasure/).check();await page.getByRole('button',{name:/Erase source payload/}).click();await expect(staged).toHaveCount(0);await expect(reports).toContainText('Fictional browser second validation');
 await page.reload();await page.getByRole('button',{name:new RegExp(datasetKey)}).click();await expect(page.getByRole('alert').filter({hasText:'Source payload erased'})).toContainText('erased');await expect(reports).toContainText('Fictional browser first validation');await expect(page.locator('body')).not.toContainText(name);
});
