-- Correlation is generated by the server, never derived from a phone or OTP.
CREATE INDEX IF NOT EXISTS idx_audit_outbox_otp_attempt_age
 ON audit_outbox(created_at,entity_id)
 WHERE action IN ('OTP_REQUEST_ATTEMPT','OTP_VERIFY_ATTEMPT');
CREATE INDEX IF NOT EXISTS idx_audit_outbox_otp_outcome_operation
 ON audit_outbox((new_value->>'operationId'))
 WHERE action IN ('OTP_REQUEST_OUTCOME','OTP_VERIFY_OUTCOME','LOGIN');
