'use client';
import Link from 'next/link';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {useAuth} from '../../context/auth-context';
import {ApiClient} from '../../lib/api-client';
interface Revision {document_id:string;revision:number;state:string;title_nepali:string;title_english:string|null;content_nepali:string;content_english:string|null;category:string;keywords:string[];provenance:string;author_id:string;reviewer_id:string|null;approved_by:string|null;approved_at:string|null;published_at:string|null}
interface Document extends Revision {id:string;slug:string;version:number;designated_approver_id:string|null}
interface Page<T>{items:T[];nextBefore:string|null}
interface Event {sequence:string;revision:number;action:string;actor_id:string;reason:string;created_at:string}
const empty={slug:'',titleNepali:'',titleEnglish:'',contentNepali:'',contentEnglish:'',category:'HISTORY',keywords:'',provenance:''};
export default function CulturalPage(){
 const {accessToken,user,isLoading}=useAuth();const current=useRef(accessToken);current.current=accessToken;
 const [documents,setDocuments]=useState<Document[]>([]),[published,setPublished]=useState<any[]>([]),[query,setQuery]=useState('');
 const [form,setForm]=useState(empty),[editing,setEditing]=useState<Document|null>(null),[reason,setReason]=useState(''),[approver,setApprover]=useState('');
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState<Page<Revision>|null>(null),[events,setEvents]=useState<Page<Event>|null>(null),[selected,setSelected]=useState<Document|null>(null);
 const editor=!!user?.roles.some(r=>['SUPER_ADMIN','CENTRAL_ADMIN','CULTURAL_HISTORIAN'].includes(r));const admin=!!user?.roles.some(r=>['SUPER_ADMIN','CENTRAL_ADMIN'].includes(r));
 async function load(token:string,q=''){
  const [docs,articles]=await Promise.all([ApiClient.cultural<Document[]>('/documents',token),ApiClient.cultural<any[]>(`/published${q?`?q=${encodeURIComponent(q)}`:''}`,token)]);
  if(current.current!==token)return;setDocuments(docs);setPublished(articles);
 }
 useEffect(()=>{setDocuments([]);setPublished([]);setForm(empty);setEditing(null);setHistory(null);setEvents(null);setSelected(null);setReason('');setApprover('');setError('');setBusy(false);if(accessToken)void load(accessToken).catch(e=>{if(current.current===accessToken)setError(e.message);});},[accessToken]);
 async function action(work:(token:string)=>Promise<void>){if(!accessToken)return;const token=accessToken;setBusy(true);setError('');try{await work(token);if(current.current===token)await load(token,query);}catch(e){if(current.current===token)setError((e as Error).message);}finally{if(current.current===token)setBusy(false);}}
 async function submit(e:FormEvent){e.preventDefault();await action(async token=>{const body={titleNepali:form.titleNepali,contentNepali:form.contentNepali,category:form.category,keywords:form.keywords.split(',').map(k=>k.trim()).filter(Boolean),provenance:form.provenance,...form.titleEnglish?{titleEnglish:form.titleEnglish}:{},...form.contentEnglish?{contentEnglish:form.contentEnglish}:{},...editing?{version:editing.version,reason}:{slug:form.slug}};
  await ApiClient.cultural(editing?`/documents/${editing.id}/revisions`:'/documents',token,'POST',body);if(current.current===token){setForm(empty);setEditing(null);setHistory(null);setEvents(null);}});}
 function edit(d:Document){setEditing(d);setForm({slug:d.slug,titleNepali:d.title_nepali,titleEnglish:d.title_english||'',contentNepali:d.content_nepali,contentEnglish:d.content_english||'',category:d.category,keywords:d.keywords.join(', '),provenance:d.provenance});}
 async function inspect(d:Document,before?:string,eventBefore?:string){await action(async token=>{const [h,e]=await Promise.all([ApiClient.cultural<Page<Revision>>(`/documents/${d.id}/history${before?`?before=${before}`:''}`,token),ApiClient.cultural<Page<Event>>(`/documents/${d.id}/events${eventBefore?`?before=${eventBefore}`:''}`,token)]);if(current.current===token){setSelected(d);setHistory(h);setEvents(e);}});}
 function transition(d:Document,a:string){void action(async token=>{await ApiClient.cultural(`/documents/${d.id}/transition`,token,'POST',{version:d.version,revision:d.revision,action:a,reason});if(current.current===token){setHistory(null);setEvents(null);}});}
 if(isLoading)return <p>लोड हुँदैछ (Loading)…</p>;if(!accessToken)return <p><Link href="/login?next=/cultural">संस्कृति हेर्न प्रवेश गर्नुहोस् (Sign in to view cultural content).</Link></p>;
 const field=(key:keyof typeof empty,label:string,max:number,required=false,multiline=false)=><label className="block" key={key}>{label}{multiline?<textarea className="block border rounded p-2 w-full" rows={5} maxLength={max} required={required} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input className="block border rounded p-2 w-full" maxLength={max} required={required} readOnly={key==='slug'&&!!editing} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>;
 return <section className="max-w-4xl space-y-5"><h1 className="text-2xl font-bold">संस्कृति तथा इतिहास (Culture and history)</h1><p>प्रकाशन अघि स्वतन्त्र समीक्षा र तोकिएको प्रतिनिधिको स्वीकृति चाहिन्छ (Publication requires independent review and designated representative approval).</p>
 {error&&<p role="alert" className="bg-red-50 text-red-800 p-3">{error}</p>}
 <form onSubmit={e=>{e.preventDefault();void action(t=>load(t,query));}} className="flex gap-3"><label>खोज (Search)<input className="border p-2 block" maxLength={120} value={query} onChange={e=>setQuery(e.target.value)}/></label><button disabled={busy}>खोज्नुहोस् (Search published content)</button></form>
 <div>{published.map(a=><article key={a.id} className="border rounded bg-white p-4 my-3"><h2 className="font-bold">{a.title_nepali} {a.title_english}</h2><p className="whitespace-pre-wrap">{a.content_nepali}</p>{a.content_english&&<p className="whitespace-pre-wrap">{a.content_english}</p>}<p>संस्करण (Revision): {a.version} · {a.published_at}</p><p>स्रोत (Source): {a.provenance}</p></article>)}</div>
 {editor&&<form onSubmit={submit} aria-label="Cultural draft" className="border rounded bg-white p-5 space-y-3"><h2 className="font-bold">{editing?'नयाँ संस्करण (New revision)':'मस्यौदा (New draft)'}</h2>
 {field('slug','ठेगाना (URL slug)',120,true)}{field('titleNepali','नेपाली शीर्षक (Nepali title)',255,true)}{field('titleEnglish','अङ्ग्रेजी शीर्षक (English title)',255)}{field('contentNepali','नेपाली सामग्री (Nepali content)',50000,true,true)}{field('contentEnglish','अङ्ग्रेजी सामग्री (English content)',50000,false,true)}{field('category','प्रकार (Category)',50,true)}{field('keywords','मुख्य शब्द (Comma-separated keywords)',1600)}{field('provenance','स्रोत र प्रमाण (Source and evidence)',4000,true,true)}
 <button disabled={busy} className="border rounded p-2">मस्यौदा सुरक्षित गर्नुहोस् (Save draft)</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty);}}>रद्द (Cancel editing)</button>}</form>}
 {documents.length>0&&<label className="block">निर्णय / परिवर्तनको कारण (Decision / change reason)<textarea className="border p-2 block w-full" maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label>}
 {admin&&documents.length>0&&<label className="block">तोकिएको प्रतिनिधिको खाता ID (Designated representative account ID)<input className="border p-2 block w-full" value={approver} onChange={e=>setApprover(e.target.value)}/></label>}
 {documents.map(d=><article key={d.id} className="border rounded bg-white p-5 space-y-3"><h2 className="font-bold">{d.title_nepali} · {d.slug}</h2><p>संस्करण (Revision) {d.revision} · {d.state} · परिवर्तन (Document version) {d.version}</p><p>Author: {d.author_id} · Reviewer: {d.reviewer_id||'Pending'} · Approver: {d.designated_approver_id||'Unassigned'}</p>
 <div className="flex flex-wrap gap-3">
 {editor&&['DRAFT','PUBLISHED','ARCHIVED','SUPERSEDED'].includes(d.state)&&<button disabled={busy} onClick={()=>edit(d)}>संस्करण तयार गर्नुहोस् (Prepare revision)</button>}
 {admin&&['DRAFT','REVIEW'].includes(d.state)&&<button disabled={busy||!reason.trim()||!approver.trim()} onClick={()=>void action(async token=>{await ApiClient.cultural(`/documents/${d.id}/approver`,token,'POST',{version:d.version,approverId:approver,reason});})}>प्रतिनिधि तोक्नुहोस् (Assign approver)</button>}
 {editor&&d.state==='DRAFT'&&<button disabled={busy||!reason.trim()} onClick={()=>transition(d,'SUBMIT')}>समीक्षामा पठाउनुहोस् (Submit for review)</button>}
 {editor&&d.state==='REVIEW'&&!d.reviewer_id&&d.author_id!==user?.id&&d.designated_approver_id!==user?.id&&<button disabled={busy||!reason.trim()} onClick={()=>transition(d,'REVIEW')}>समीक्षा समर्थन (Endorse review)</button>}
 {editor&&['REVIEW','APPROVED'].includes(d.state)&&<button disabled={busy||!reason.trim()} onClick={()=>transition(d,'RETURN')}>मस्यौदामा फर्काउनुहोस् (Return to draft)</button>}
 {d.state==='REVIEW'&&d.reviewer_id&&d.designated_approver_id===user?.id&&<button disabled={busy||!reason.trim()} onClick={()=>transition(d,'APPROVE')}>प्रतिनिधिको स्वीकृति (Approve as representative)</button>}
 {editor&&d.state==='APPROVED'&&<button disabled={busy||!reason.trim()} onClick={()=>transition(d,'PUBLISH')}>प्रकाशन (Publish)</button>}
 {editor&&d.state==='PUBLISHED'&&<button disabled={busy||!reason.trim()} onClick={()=>transition(d,'ARCHIVE')}>सङ्ग्रह (Archive)</button>}
 <button disabled={busy} onClick={()=>void inspect(d)}>इतिहास र प्रमाण (History and evidence)</button></div></article>)}
 {selected&&history&&<section aria-label="Revision history" className="border rounded p-4"><h2>संस्करण इतिहास (Revision history) · {selected.slug}</h2>{history.items.map(r=><article key={r.revision} className="border p-3"><h3>{r.revision} · {r.state} · {r.title_nepali}</h3><p className="whitespace-pre-wrap">{r.content_nepali}</p>{r.content_english&&<p className="whitespace-pre-wrap">{r.content_english}</p>}<p>Author: {r.author_id} · Reviewer: {r.reviewer_id} · Approval: {r.approved_by} {r.approved_at} · Published: {r.published_at}</p><p>Source: {r.provenance}</p></article>)}{history.nextBefore&&<button disabled={busy} onClick={()=>void inspect(selected,history.nextBefore!)}>अघिल्लो संस्करण (Older revisions)</button>}</section>}
 {selected&&events&&<section aria-label="Content decisions"><h2>निर्णय इतिहास (Decision history)</h2>{events.items.map(e=><p key={e.sequence}>#{e.sequence} · Revision {e.revision} · {e.action} · {e.actor_id} · {e.reason} · {e.created_at}</p>)}{events.nextBefore&&<button disabled={busy} onClick={()=>void inspect(selected,undefined,events.nextBefore!)}>अघिल्ला निर्णय (Older decisions)</button>}</section>}
 </section>;
}
