'use client';
import { useCallback, useEffect, useState } from 'react';
import { useAuth } from '../../context/auth-context';
const API=process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:3000';
export default function AuditPage(){
 const {accessToken,isLoading}=useAuth();const [items,setItems]=useState<any[]>([]),[next,setNext]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [integrity,setIntegrity]=useState<any>(null);
 const [action,setAction]=useState(''),[entity,setEntity]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const load=useCallback(async(cursor?:string)=>{if(isLoading||!accessToken)return;setBusy(true);setError('');try{
  const q=new URLSearchParams({...action?{action}:{},...entity?{entityId:entity}:{},...from?{from:new Date(from).toISOString()}:{},...to?{to:new Date(to).toISOString()}:{},...cursor?{cursor}:{}});
  const r=await fetch(`${API}/audit?${q}`,{headers:{Authorization:`Bearer ${accessToken}`}});const data=await r.json();if(!r.ok)throw new Error(data.message||'Audit unavailable');setItems(prev=>cursor?[...prev,...data.items]:data.items);setNext(data.nextCursor);
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}},[accessToken,isLoading,action,entity,from,to]);
 async function verify(){if(!accessToken||isLoading)return;setBusy(true);setError('');try{const r=await fetch(`${API}/audit/integrity`,{headers:{Authorization:`Bearer ${accessToken}`}});const data=await r.json();if(!r.ok)throw new Error(data.message||'Verification unavailable');setIntegrity(data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[accessToken,isLoading]);
 return <section className="space-y-4"><h1 className="text-2xl font-bold">अडिट इतिहास (Audit history)</h1><p>Saved audit metadata. Restricted evidence and message bodies are excluded from this view.</p>{error&&<p role="alert" className="text-red-800">{error}</p>}
  <div className="space-y-2"><button disabled={busy||isLoading||!accessToken} onClick={()=>void verify()} className="border rounded p-2">Verify audit integrity</button>{integrity&&<p role="status">{integrity.status} · {integrity.verifiedRecords} verified records · {integrity.legacyRecords} historical records unverified{integrity.failure?` · ${integrity.failure.reason}`:''}</p>}<p className="text-sm text-slate-600">Verification checks the stored chain. Older hashes are preserved and reported separately. External backups are required to detect privileged database replacement.</p></div>
  <form className="flex gap-3 flex-wrap" onSubmit={e=>{e.preventDefault();void load();}}><label>Action<input value={action} onChange={e=>setAction(e.target.value)} className="block border p-2 rounded"/></label><label>Entity ID<input value={entity} onChange={e=>setEntity(e.target.value)} className="block border p-2 rounded"/></label><label>From<input type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)} className="block border p-2 rounded"/></label><label>To<input type="datetime-local" value={to} onChange={e=>setTo(e.target.value)} className="block border p-2 rounded"/></label><button disabled={busy} className="border rounded p-2">Search audit history</button></form>
  <div className="overflow-x-auto"><table className="w-full text-sm text-left"><caption className="sr-only">Persisted audit records</caption><thead><tr>{['Time','Action','Entity','Actor','Record hash'].map(h=><th key={h} className="p-3 border-b">{h}</th>)}</tr></thead><tbody>{items.map(row=><tr key={row.id}><td className="p-3 border-b">{new Date(row.createdAt).toLocaleString()}</td><td className="p-3 border-b">{row.action}</td><td className="p-3 border-b">{row.entityType}<br/>{row.entityId}</td><td className="p-3 border-b">{row.actorRole||'System'}</td><td className="p-3 border-b font-mono" title={row.currentRecordHash}>{row.currentRecordHash.slice(0,16)}…</td></tr>)}</tbody></table></div>{!items.length&&!busy&&!error&&<p>No records match these filters.</p>}{next&&<button disabled={busy} onClick={()=>void load(next)} className="border rounded p-3">Load older records</button>}
 </section>;
}
